# Default values for solr.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
image: "solr"
imagePullPolicy: "Always"
command: "[\"solr\"]"
args: "[\"-f\", \"-c\", \"-m\", \"2g\", \"-z\", \"zookeeper-zookeeper:2181\"]"
replicas: 3
minAvailable: 2
containerPort: 8983
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: 1
    memory: "4Gi"
heap: "2G"
storage: "50Gi"
# storageClass: default
tickTimeMs: 2000
initTicks: 10
syncTicks: 5
clientCnxns: 60
snapRetain: 3
purgeHours: 1
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
antiAffinity: "hard"
logLevel: "INFO"
security:
  enabled: false
  runAsUser: 1000
  fsGroup: 1000
